# Generated by Django 4.0.3 on 2023-06-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_answer_modify_count_question_modify_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='modify_count',
            field=models.IntegerField(default=0),
        ),
    ]
